#!/bin/bash
# Script to make a picture from the step-wise output of linelife. This can be
# thought of as a 2-dimensional presentation where the other dimension is time.
# The patterns are taken from stdin (and they should be in the format linelife
# produces).
# Usage something like:
#  ./linel 11001101101 -n 20 -s | ./llpicture.sh
#
# Requires awk and some other standard utilities.
# The output will be a .pbm-file, printed in stdout.
#

#Start header:
echo "P1"
echo "#generated by llpicture on $(date)"

#Store everything except "summary line", remove all but patterns and shifts:
head -n -1 | sed 's/^.* shift //' | sed 's/)://' > llp_tmp
#Find minimum shift value (giving the position of the left edge):
minshift=$(awk 'm=="" || $1 < m {m=$1} END{print m}' FS=" " llp_tmp)
#Find maximum [shift]+[length] value (giving right edge position):
maxright=$(awk 'm=="" || $1+length($2) > m {m=$1+length($2)}\
	END{print m}' FS=" " llp_tmp)

#Finish header (dimensions; rows, cols):
echo "$(expr $maxright - $minshift) $(wc -l llp_tmp | cut -f 1 -d ' ')"

# Add the required amount of '0's to each line. Just print out the result, as it 
# is already in the correct format for pbm images.
awk "{for(i = \$1; i > $minshift; --i) printf \"0\"; printf \"%s\", \$2;\
	for(i = \$1+length(\$2); i < $maxright; ++i) printf \"0\";\
	print \"\"}" FS=" " llp_tmp

# Remove temporary file:
rm -f llp_tmp

